# Generated by Django 5.1.7 on 2025-03-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasuki_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.PositiveIntegerField(default=0)),
                ('projects', models.PositiveIntegerField(default=0)),
                ('hours_of_support', models.PositiveIntegerField(default=0)),
                ('hard_workers', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
