# Generated by Django 5.1.7 on 2025-03-12 06:01

import meta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasuki_app', '0002_homestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
